
ForumsRes = 
{
    
    url_transGif: "http://i1.social.s-msft.com/Forums/../globalresources/Images/trans.gif?cver=0%0d%0a",
    nt_Alert_disabled: 'This feature is not enabled for this forum',
    nt_Tags_disabled: 'This feature is not enabled for this forum',
    prompt_clearAbuseReason: 'Reason for clearing\x3f',
    prompt_deleteReason: 'Reason for delete\x3f',
    prompt_escalateReason: 'Reason for escalation\x3f',
    prompt_deEscalateReason: 'Reason for de-escalation\x3f',
    prompt_markAllRead: 'This will mark all threads as read. Once applied original unread state cannot be reapplied. Are you sure you want to continue\x3f',
    prompt_pageExit: 'If you have made any changes to the fields without clicking the Submit button, your changes will be lost.  Are you sure you want to exit this page\x3f',
    prompt_reportAbuseReason: 'Reason for reporting\x3f',
    prompt_stickyUntil: 'Sticky Until Date \x28yyyy-mm-dd\x29\x3f',
    prompt_undeleteReason: 'Reason for undelete\x3f',
    rte_alreadyOpen: 'You already have a reply open, please close before continuing.',
    rte_cancelText: 'Cancel',
    rte_OKText: 'Submit',
    rte_reasonLabel: 'Reason',
    rte_subjectLabel: 'Title',
    rte_submitText: 'Submit',
    rte_subscribeText: '\x3cb\x3eAlert me\x3c\x2fb\x3e when someone responds to this post.',
    rte_readyDelay: 100,
    thread_closePreviewText: '\x28close thread\x29',
    thread_viewThreadText: '\x28view thread\x29',
    get_editorUrl: "/forums/telerik/GetEditorHtml",
    url_loadingimg: "http://i1.social.s-msft.com/Forums/resources/images/loading.gif?cver=0%0d%0a",
    rte_updateText: 'Update',
    rte_uploadText: 'Upload',
    rte_insertText: 'Insert',
    rte_InsertHtml: 'Insert HTML',
    rte_InsertCodeBlock: 'Insert Code Block',
    rte_CodeLanguageLabel: 'Language',
    rte_PreviewButtontext: 'Preview',
    rte_SelectLanguage: 'Select Language',
    rte_wordWrap: 'Word wrap',
    rte_msgBodyLength: 'Body must be 4 to 60000 characters long.',
    rte_MaxAttachments: '2',
    rte_MaxFileSize: '1024',
    rte_MaxAttachmentsErrMsg:'You can upload only 2 Images per message.',
    rte_msgInsertImageCondition: 'Maximum allowed image size is 1024 KB. You can upload only 2 Images per message.',
    rte_InsertImageText: 'Insert image',
    rte_AlternateText: 'Alternate text',
    rte_CloseText: 'Close',
    rte_ImageUrlText: 'Image URL',
    StickyDateInValid: 'Invalid Date Format. Please use \x28yyyy-mm-dd\x29',
    MessageBodyUnTrustedUser: 'Body text cannot contain images or links until we are able to verify your account.',
    SpamMessage: 'Your post has been flagged and is currently under additional verification. If you believe that this was done in error, please post to the thread \x3ca href\x3d\x22\x7b0\x7d\x22\x3eHERE\x3c\x2fa\x3e.',
    UnexpectedError: 'Unexpected Error',
    UserNameRequired: 'User display name is required.',
    Announcement_CloseText: 'Close',
    Announcement_LinkToAnnouncement: 'Link to this announcement'
}